version: '3.4'

services:
  kazanexpress:
    image: kazanexpress
    container_name: kazanexpress
    env_file:
      - .env
    ports:
      - 9000:${PORT}
    volumes:
      - kazanexpress-data:/app

    environment:
      - PORT=${PORT}
      - TG_USERID=${TG_USERID}
      - TG_TOKEN=${TG_TOKEN}
volumes:
  kazanexpress-data:
